if(EXISTS "/home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests_tests-b12d07c.cmake")
  include("/home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests_tests-b12d07c.cmake")
else()
  add_test(unit_tests_NOT_BUILT-b12d07c unit_tests_NOT_BUILT-b12d07c)
endif()
