add_test( [==[RGBA to RGB565 known colors]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[RGBA to RGB565 known colors]==]  )
set_tests_properties( [==[RGBA to RGB565 known colors]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[RGBA to RGB565 mixed sample]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[RGBA to RGB565 mixed sample]==]  )
set_tests_properties( [==[RGBA to RGB565 mixed sample]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[PIDBindingSystem register and default value]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[PIDBindingSystem register and default value]==]  )
set_tests_properties( [==[PIDBindingSystem register and default value]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[PIDBindingSystem scales and clamps values]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[PIDBindingSystem scales and clamps values]==]  )
set_tests_properties( [==[PIDBindingSystem scales and clamps values]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[PIDBindingSystem format_value returns numeric string]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[PIDBindingSystem format_value returns numeric string]==]  )
set_tests_properties( [==[PIDBindingSystem format_value returns numeric string]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[BinaryGaugeLoader parses minimal valid buffer]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[BinaryGaugeLoader parses minimal valid buffer]==]  )
set_tests_properties( [==[BinaryGaugeLoader parses minimal valid buffer]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[BinaryGaugeLoader rejects wrong magic or version]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[BinaryGaugeLoader rejects wrong magic or version]==]  )
set_tests_properties( [==[BinaryGaugeLoader rejects wrong magic or version]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
add_test( [==[TileHeightRenderer renders tiles via test callback]==] /home/c4tachan/projects/digi-dash/simulator/build_test/unit_tests [==[TileHeightRenderer renders tiles via test callback]==]  )
set_tests_properties( [==[TileHeightRenderer renders tiles via test callback]==] PROPERTIES WORKING_DIRECTORY /home/c4tachan/projects/digi-dash/simulator/build_test)
set( unit_tests_TESTS [==[RGBA to RGB565 known colors]==] [==[RGBA to RGB565 mixed sample]==] [==[PIDBindingSystem register and default value]==] [==[PIDBindingSystem scales and clamps values]==] [==[PIDBindingSystem format_value returns numeric string]==] [==[BinaryGaugeLoader parses minimal valid buffer]==] [==[BinaryGaugeLoader rejects wrong magic or version]==] [==[TileHeightRenderer renders tiles via test callback]==])
